FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.* ./
RUN go mod tidy

COPY . .
RUN cd /app/stock-proxy && CGO_ENABLED=0 GOOS=linux go build -o /stock-proxy-app .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY --from=builder /stock-proxy-app .

# Cloud Run port
EXPOSE 8080
CMD ["./stock-proxy-app"]
