FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.* ./
RUN go mod tidy

COPY . .
RUN cd /app/api-gateway && CGO_ENABLED=0 GOOS=linux go build -o /api-gateway-app .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY --from=builder /api-gateway-app .

# Cloud Run port (8080)
EXPOSE 8080
CMD ["./api-gateway-app"]
