# Development Dockerfile for Cleanup
FROM golang:1.24

# protoc
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN export PATH="$PATH:$(go env GOPATH)/bin"

# [Optional] Uncomment this section to install additional OS packages.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends protobuf-compiler

# neovim
RUN curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
RUN rm -rf /opt/nvim
RUN tar -C /opt -xzf nvim-linux-x86_64.tar.gz
RUN cp -r /opt/nvim-linux-x86_64/bin/* /usr/local/bin/
RUN cp -r /opt/nvim-linux-x86_64/lib/* /usr/local/lib/
RUN cp -r /opt/nvim-linux-x86_64/share/* /usr/local/share/
RUN rm -rf /opt/nvim-linux-x86_64

# gcloud cli
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg && apt-get update -y && apt-get install google-cloud-cli -y

# bash completion
RUN echo "source /etc/profile.d/bash_completion.sh" >> ~/.bashrc
